LINKEDIN_USERNAME = '[id="username"]'
LINKEDIN_PASSWORD = '[id="password"]'
LINKEDIN_SIGN_IN = '[aria-label="Sign in"]'
LINKEDIN_FEED_PAGE_PROFILE_SECTION = '[class="profile-card-member-details"]'
LINKEDIN_EDIT_BUTTON = '[href="#edit-medium"]'
LINKEDIN_SAVE_PROFILE = '[data-view-name="profile-form-save"]'
LINKEDIN_JOB_SECTION = '[type="job"]'
LINKEDIN_JOB_TITLE= '[role="combobox"]'
LINKEDIN_JOB_SECTION_SIDE_BAR = '[class="jobs-home-scalable-nav"]'
DATE_POSTED_FILTER_OPTIONS = '[aria-label="Date posted filter. Clicking this button displays all Date posted filter options."]'
DATE_POSTED_LAST_ONE_DAY = '//span[text()="Past 24 hours"]'
APPLY_DATE_POSTED_FILTER = '[class="artdeco-button artdeco-button--2 artdeco-button--primary ember-view ml2"]'
EASY_APPLY_FILTER = '[id="searchFilter_applyWithLinkedin"]'
LINKEDIN_JOB_POST = '[data-view-name="job-card"]'
LINKEDIN_APPLY_BUTTON = '[id="jobs-apply-button-id"]'
NEXT_BUTTON = '//span[@class="artdeco-button__text" and text()="Next"]'
MANDATORY_NOT_FILLED_ERROR = 'li-icon[type="error-pebble-icon"]'
REVIEW_BUTTON = '//span[@class="artdeco-button__text" and text()="Review"]'
LINKEDIN_SUBMIT_APPLICATION = '//span[@class="artdeco-button__text" and text()="Submit application"]'
LINKEDIN_KEEP_ME_LOGGED_IN = '[id="rememberMeOptIn-checkbox"]'
CLOSE_APPLICATION = '[data-test-icon="close-medium"]'