LOGIN_BUTTON = '[id="login_Layer"]'
USERNAME_INPUT = '[placeholder="Enter your active Email ID / Username"]'
PASSWORD_INPUT = '[placeholder="Enter your password"]'
SUBMIT_BUTTON = '//button[@type="submit" and text()="Login"]'
JOB_SEARCH_START = '//span[text()="Search jobs here"]'
VIEW_PROFILE = '//div[@class="view-profile-wrapper"]/a'
PROFILE_NAME = '//span[@class="fullname"]'
PROFILE_PERCENTAGE_VALUE = '//div[contains(@class, "user-percentage")]'
JOB_SEARCH_KEYWORD = '[placeholder="Enter keyword / designation / companies"]'
JOB_SEARCH_LOCATION = '[placeholder="Enter location"]'
SEARCH_BUTTON = '//span[text()="Search"]'
FILTER_FRESHNESS = '#filter-freshness'
FILTER_FRESHNESS_LAST_1_DAY = '//span[text()="Last 1 day"]'
JOB_POSTS = '[class="cust-job-tuple layout-wrapper lay-2 sjw__tuple "]'
APPLY_ON_COMPANY_SITE_BUTTON = '[id="company-site-button"]'
APPLIED_FILTERS = '//a[contains(@class, "styles_appliedTxt__UmIjs") and normalize-space(.)="Applied (1)"]'
NAUKRI_INTERNAL_APPLY_BUTTON = '//button[@id="apply-button"]'
ANSWER_PLACEHOLDER = 'div.textArea[contenteditable="true"]'
JOB_ALREADY_APPLIED = '[id="already-applied"]'
QUESTION_1 = '//span[text()="How much experience do you have in Python?"]'
QUESTION_2 = '//span[text()="How many years of Exp in Automation Python testing?"]'
QUESTION_3 = '//span[text()="How many years of total experience you have?"]'
QUESTION_4 = '//span[text()="What is your expected CTC in Lakhs per annum?"]'
JOB_APPLY_PAGINATION = 'div.styles_pages__v1rAK a'
JOB_APPLY_SUCCESS = '[class="apply-message"]'